module.exports = {
    PRODUCTS_COLLECTION: 'products',
    USERS_COLLECTION: 'users',
    ADMIN_COLLECTION: 'admin',
    CART_COLLECTION: 'cart',
    ORDER_COLLECTION: 'order',
    BUILDER_COLLECTION: "builder",
    WORKSPACE_COLLECTION: "workspace",
    FEEDBACK_COLLECTION: "feedback",
    NOTIFICATIONS_COLLECTION: "notification",
    OFFICERS_COLLECTION: 'officer',
    FAMILY: 'family-members',
    FACILITIE_COLLECTION: "facilitie",
    CONTACT_COLLECTION: "emergency-contacts",
    EVENT_COLLECTION: 'events',
    ACTIVITY_COLLECTION: 'activities',
    GALLERY_COLLECTION: 'gallery',
    FACILITIE_BOOKINGS: 'bookings',
    TEMPUSERS_COLLECTION: "temp-users",
    MCONTACT_COLLECTION: "maintainence-contacts",
    POLL_COLLECTION: "polls",
    SURVEY_COLLECTION: "survey",
    SURVEY_ANS_COLLECTION: "survey-answer",
    POLL_ANS_COLLECTION: "poll-answer",
    ADS_COLLECTION: "ads",

}